/**
 * Validation limits for scheduled notification API.
 */

export const VALIDATION_LIMITS = {
  TITLE_MAX: 200,
  MESSAGE_MAX: 1000,
  NOTIFICATION_TYPE_MAX: 50,
  DEVICE_TOKEN_MAX: 512,
  CLIENT_EVENT_ID_MIN: 8,
  CLIENT_EVENT_ID_MAX: 64,
  SCREEN_MAX: 100,
  USER_ID_MAX: 100,
  DELIVERED_LIST_LIMIT_MAX: 30,
  BULK_READ_IDS_MAX: 100,
  SCHEDULED_AT_PAST_TOLERANCE_MS: 5000,
} as const;

export const REMINDER_SYNC_FIRE_WINDOW = {
  LOOK_BEHIND_MS: 60 * 60 * 1000,
  LOOK_AHEAD_MS: 36 * 60 * 60 * 1000,
  ENQUEUE_LEAD_MS: 2000,
} as const;
